FROM python:3.11.4-slim-bullseye

# Set up a new user named "user" with user ID 1000
RUN useradd -m -u 1000 user

USER user

# Set home to the user's home directory
ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/backend

# Install poetry
RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

COPY --chown=user ./backend/pyproject.toml ./backend/poetry.lock $HOME/backend/
COPY --chown=user ./backend /backend

RUN poetry install --without dev && \
    rm -rf /tmp/poetry_cache

COPY --chown=user ./backend $HOME/backend

# Change to the package directory
WORKDIR $HOME/backend/backend

CMD ["poetry", "run", "python", "run.py"]
