name: Check file size

on:               # or directly `on: [push]` to run the action on every push on any branch
  pull_request:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:
  # to run this workflow from another workflow
  workflow_call:

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check large files
        uses: ppremk/lfs-warning@v3.2
        with:
          filesizelimit: 10MB # this is 10MB so we can sync to HF Spaces
