# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Tests

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # to run this workflow from another workflow
  workflow_call:
    secrets:
      SUPABASE_URL:
        required: true
      SUPABASE_SERVICE_ROLE_KEY:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install
    - name: Disable Next.js Telemetry
      working-directory: ./frontend
      run: npx next telemetry disable
    - name: Test Build Package
      working-directory: ./frontend
      run: npm run build --if-present
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  # - name: Run Test
    # working-directory: ./frontend
    # run: npm test
