name: Pipeline [Test, Build, Deploy]

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-file-size:
    uses: ./.github/workflows/check-file-size.yml
  test-build-node-js-app:
    uses: ./.github/workflows/node-js-tests.yml
  test-build-python-package:
    uses: ./.github/workflows/python-tests.yml
  sync-to-deployment-fork:
    needs: [test-build-node-js-app, test-build-python-package]
    uses: ./.github/workflows/sync-to-deployment-fork.yml
    secrets:
      PAT: ${{ secrets.PAT }}
  sync-to-hugging-face-hub-spaces:
    needs: [test-build-node-js-app, test-build-python-package]
    uses: ./.github/workflows/sync-to-hugging-face-hub.yml
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}